### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by calvinti12** [jesseditson/reply#4]
Got error posting tweet:  Could not authenticate you.  with response: { errors: [ { code: 32, message: 'Could not authenticate you.' } ],

**Comment by jesseditson** [comment]
I think I've seen this in the wild with accounts that twitter suspends/bans for various reasons. If you post many of the same message, eventually twitter cuts it off. I'd verify that you can post tweets manually via the API using the credentials you're using with `reply`. Something like http://140dev.com/twitter-api-console/ may make this easier to verify. Otherwise, this is just simply a credentials issue.
